services:
  backend:
    build:
      # Build the backend image using the Dockerfile inside ./backend.
      context: ./backend

    container_name: ai_analyst_backend

    # Your code is mounted directly into the container.
    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    env_file:
      - .env

    # Start the AI service before starting the backend.
    depends_on:
      - db
      - ai-service

  ai-service:
    build:
      context: ./ai-service

    container_name: ai_analyst_ai_service

    volumes:
      - ./ai-service:/app

    ports:
      - "8001:8001"
    
  db:
    image: postgres:16
    container_name: ai_analyst_db
    environment:
      POSTGRES_DB: ai_analyst
      POSTGRES_USER: ai_analyst
      POSTGRES_PASSWORD: ai_password
    
    ports:
      - "5433:5432"

    #Inside the PostgreSQL container, PostgreSQL stores its actual database files at:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_analyst -d ai_analyst"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: